### ISSUE TITLE
"The Common Form team" link shows empty if not logged in (or on team?)

### ISSUE THREAD

**Issue by anseljh** [commonform/commonform.github.io#4]
...because team members are all private. Suggest we go public--I'm fine with that.

**Comment by kemitchell** [comment]
It's a per-user setting. I've just made my own membership public. @tbrooke, would you like to do the same?

**Comment by tbrooke** [comment]
Done -

**Comment by kemitchell** [comment]
I've just invited @rickcolosimo, who's provided a great deal of useful input and feedback.
