### ISSUE TITLE
Typo in the homepage copy

### ISSUE THREAD

**Issue by sirvine** [commonform/commonform.github.io#8]
Should be "...if you'd like..."

(Happy to do PR's as I work my way through the docs, if you prefer.)

https://github.com/commonform/commonform.github.io/blob/5ac82adf5169fb035a21d9e6facac014159d85eb/index.html#L30

**Comment by kemitchell** [comment]
@sirvine, I've just added you to the https://github.com/commonform organization.

Feel free to send PRs when you'd like to bring something to my or others' attention. If you spot something that just need a fixin', just push straight to master.
